version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_tracker
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - "3307:3306"  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10  
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: expense_tracker
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql_data:
